[package]
name = "test_rust"
version = "0.1.0"
edition = "2021"

[workspace]
# Empty workspace to prevent inheriting from parent

[[bin]]
name = "bisenet_engine"
path = "src/bisenet_engine.rs"

[[bin]]
name = "test_rust"
path = "src/main.rs"

[dependencies]
libloading = "0.8"
image = "0.25"
